### ISSUE TITLE
Package react-native-nearby-api not installable both using npm and yarn

### ISSUE THREAD

**Issue by netlopa** [badfeatures/react-native-nearby-api#16]
I tried to use the react-native-nearby-api but it's not installing.

I tried these commands:

_yarn react-native-nearby-api_ 

_npm install react-native-nearby-api_

But none of them is working, and if I go to npm website there is a 404. How it's possible? Thank you

**Comment by jacks205** [comment]
This has been resolved in [v0.0.5](https://www.npmjs.com/package/react-native-nearby-api)

`yarn add react-native-nearby-api`

`npm install react-native-nearby-api`

Give it another try and see if you still experience the same issue.
